[shell.animation]
enabled = false

[wallpaper.default]
path = "/usr/share/sparrow/day-forest-path.png"

[bar.default]
concave_edge_corners = false
margin_ends = 0
position = "bottom"
radius = 0
start = [ "launcher", "wallpaper", "workspaces", "taskbar" ]

[dock]
cross_axis_padding = 0
icon_size = 16
inactive_opacity = 0.84999998100101948
inactive_scale = 1.0
launcher_position = "start"
main_axis_padding = 0
margin_edge = 5
radius = 0
show_dots = true

[lockscreen_widgets]
enabled = false

[audio]
enable_sounds = true

[shell]
corner_radius_scale = 0.0
polkit_agent = true
ui_scale = 0.85000000521540642

    [shell.panel]
    borders = false
    floating_offset = 0
    launcher_position = "bottom_center"

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kitty", "qt", "btop", "kcolorscheme" ]
    community_ids = [ "neovim", "yazi", "hyprtoolkit" ]
